// Generated by CoffeeScript 1.6.1
/*
 * flatLand! - hire me !
 *
 * COFFEE/JS Document - /js/script.coffee
 * coded by leny@flatLand!
 * started at 28/04/13
*/(function(){var e,t,n,r;if(window.isIE===!0)return;e=!!navigator.userAgent.match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile/i);t=window.devicePixelRatio>1;r=/^(.*)\.(jpg|jpeg|png|gif)$/i;n=function(){return window.scrollTo(0,1)};window.addEventListener("load",function(){var i,s,o,u,a,f,l,c,h,p;c=document.querySelectorAll('a[rel="external"]');for(u=0,f=c.length;u<f;u++){s=c[u];s.setAttribute("target","_new")}if(e)setTimeout(n,0);else{o=document.getElementById("phone");o.removeAttribute("href")}if(t){h=document.querySelectorAll("img");p=[];for(a=0,l=h.length;a<l;a++){i=h[a];p.push(i.src=i.src.replace(r,"$1_@2X.$2"))}return p}})}).call(this);